import("//build/args/headless.gn")

target_os = "linux"
target_cpu = "@TARGET_CPU@"
host_cpu = "@TARGET_CPU@"
root_extra_deps = [ "//tools/hermetic_smoke" ]

is_clang = true
is_musl = true
use_sysroot = false
rust_sysroot_absolute = "/usr"
rust_bindgen_root = "/usr"
use_lld = true
clang_base_path = "/opt/llvm-musl"
clang_version = "@CLANG_MAJOR@"
clang_use_chrome_plugins = false
custom_toolchain = "//build/toolchain/linux/unbundle:default"
host_toolchain = "//build/toolchain/linux/unbundle:default"
cc_wrapper = "/usr/bin/ccache"

is_component_build = false
is_debug = true
is_official_build = false
safe_browsing_mode = 0
symbol_level = 0
blink_symbol_level = 0
v8_symbol_level = 0
chrome_pgo_phase = 0
is_cfi = false
use_thin_lto = false
use_custom_libcxx = true
use_laputa_libcxx = true
use_safe_libstdcxx = false

use_ozone = true
ozone_platform = "headless"
ozone_platform_headless = true
use_xkbcommon = false
ozone_platform_wayland = false
use_gtk = false
use_qt6 = false
use_alsa = false
use_pulseaudio = false
rtc_use_pipewire = false
rtc_link_pipewire = false
use_vaapi = false
enable_vulkan = false
enable_swiftshader = false
enable_printing = false

ffmpeg_branding = "Chrome"
proprietary_codecs = true
enable_widevine = false

optimize_webui = false
enable_service_discovery = false
